version: 2
jobs:
    build:
        docker:
        - image: andreacensi/mcdp_books:duckuments@sha256:307d478c8cedaff574e4a94303dae779547a513bd0641e3d4c236a5206b6c77b
          environment:
              COLUMNS: 160
              TERM: xterm-256color
              EXTRA_MCDP_RENDER_OPTIONS: --ignore_ref_errors

        resource_class: large
        steps:
        - add_ssh_keys:
            fingerprints:
                - "1e:af:1c:cf:12:02:ec:5f:48:ff:06:e6:03:2b:6d:1f"
        - checkout
        - run:
            name: Download resources
            command: |
              ssh -T git@github.com
              git submodule sync --recursive
              git submodule update --init --recursive

        - run:
            name: Compile
            command: make compile-native-ci

        - run:
            name: Link check
            command: |
                . /project/deploy/bin/activate && make linkcheck || true

        - run:
            when: always
            name: Package artifacts
            command:  |
                find duckuments-dist -name '*.old' -delete
                make package-artifacts

        - store_artifacts:
              path: out/package.tgz
              destination: out/package.tgz


        - store_artifacts:
              path: duckuments-dist
              destination: duckuments-dist


        - test-results-store:
            path: duckuments-dist/junit
